[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "herbie"
author = "Hristo Filaretov"
author-email = "h.filaretov@campus.tu-berlin.de"
classifiers = ["License :: OSI Approved :: MIT License"]

